In [15]:
import numpy as np
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print("ADDITION:\n", m1 + m2)
print("SUBTRACTION:\n", m1 - m2)
print("MULTIPLICATION:\n", m1 * m2)
print("DOT PRODUCT:\n", np.dot(m1,m2))
print("METRIX TRANSPOSE:\n", m1.T)

ADDITION:
 [[ 6  8]
 [10 12]]
SUBTRACTION:
 [[-4 -4]
 [-4 -4]]
MULTIPLICATION:
 [[ 5 12]
 [21 32]]
DOT PRODUCT:
 [[19 22]
 [43 50]]
METRIX TRANSPOSE:
 [[1 3]
 [2 4]]
