In [3]:
import numpy as np
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
U, S, VT = np.linalg.svd(X)
n_components = 2
X_re = np.dot(U[:, :n_components], np.dot(np.diag(S[:n_components]), VT[:n_components, :]))
print("Original Matrix:\n", X)
print("Reconstructed Matrix with n_components=2:\n", X_re)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reconstructed Matrix with n_components=2:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
